"""Init tables

Revision ID: 6b8018f97a25
Revises:
Create Date: 2026-04-15 18:25:51.113605

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6b8018f97a25"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parts_and_materials",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nomenclature", sa.String(length=150), nullable=False),
        sa.Column("stock_quantity", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nomenclature"),
    )
    op.create_table(
        "regulations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "repair_type",
            sa.Enum("TO1", "TO2", "TO3", "TR1", "TR2", "KR", name="repairtypeenum"),
            nullable=False,
        ),
        sa.Column("standard_hours", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repair_type"),
    )
    op.create_table(
        "rolling_stocks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("inventory_number", sa.String(length=50), nullable=False),
        sa.Column("series", sa.String(length=50), nullable=False),
        sa.Column("manufacture_date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rolling_stocks_inventory_number"),
        "rolling_stocks",
        ["inventory_number"],
        unique=True,
    )
    op.create_table(
        "work_brigades",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "repair_tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("rolling_stock_id", sa.Integer(), nullable=False),
        sa.Column(
            "repair_type",
            sa.Enum("TO1", "TO2", "TO3", "TR1", "TR2", "KR", name="repairtypeenum"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("CREATED", "IN_PROGRESS", "COMPLETED", name="taskstatusenum"),
            nullable=False,
        ),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("planned_end_date", sa.DateTime(), nullable=True),
        sa.Column("actual_end_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["rolling_stock_id"],
            ["rolling_stocks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "repair_stages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("repair_task_id", sa.Integer(), nullable=False),
        sa.Column("regulation_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "IN_PROGRESS",
                "WAITING_PARTS",
                "COMPLETED",
                name="stagestatusenum",
            ),
            nullable=False,
        ),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["regulation_id"],
            ["regulations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repair_task_id"],
            ["repair_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stage_brigade_association",
        sa.Column("stage_id", sa.Integer(), nullable=False),
        sa.Column("brigade_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["brigade_id"],
            ["work_brigades.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["repair_stages.id"],
        ),
        sa.PrimaryKeyConstraint("stage_id", "brigade_id"),
    )
    op.create_table(
        "stage_part_association",
        sa.Column("stage_id", sa.Integer(), nullable=False),
        sa.Column("part_id", sa.Integer(), nullable=False),
        sa.Column("quantity_used", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["part_id"],
            ["parts_and_materials.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["repair_stages.id"],
        ),
        sa.PrimaryKeyConstraint("stage_id", "part_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stage_part_association")
    op.drop_table("stage_brigade_association")
    op.drop_table("repair_stages")
    op.drop_table("repair_tasks")
    op.drop_table("work_brigades")
    op.drop_index(
        op.f("ix_rolling_stocks_inventory_number"), table_name="rolling_stocks"
    )
    op.drop_table("rolling_stocks")
    op.drop_table("regulations")
    op.drop_table("parts_and_materials")
    # ### end Alembic commands ###
